name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: ESLint
        run: npm run eslint