name: Semgrep Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: .semgrep.yml
          
      - name: Run Semgrep
        run: semgrep --config .semgrep.yml --error --json > semgrep-report.json

